package com.seanof.sakugatomo.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF66558E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADDFF)
val onPrimaryContainerLight = Color(0xFF4E3D75)
val secondaryLight = Color(0xFF625B70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DEF8)
val onSecondaryContainerLight = Color(0xFF4A4358)
val tertiaryLight = Color(0xFF7E525F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E2)
val onTertiaryContainerLight = Color(0xFF643B47)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xE2FEF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xE2FEF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val outlineVariantLight = Color(0xFFCBC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFD1BCFD)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFEF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFECE6EE)
val surfaceContainerHighestLight = Color(0xFFE7E0E8)

val primaryDark = Color(0xFFD1BCFD)
val onPrimaryDark = Color(0xFF37265C)
val primaryContainerDark = Color(0xFF4E3D75)
val onPrimaryContainerDark = Color(0xFFEADDFF)
val secondaryDark = Color(0xFFCCC2DB)
val onSecondaryDark = Color(0xFF332D41)
val secondaryContainerDark = Color(0xFF4A4358)
val onSecondaryContainerDark = Color(0xFFE9DEF8)
val tertiaryDark = Color(0xFFF0B8C6)
val onTertiaryDark = Color(0xFF4A2531)
val tertiaryContainerDark = Color(0xFF643B47)
val onTertiaryContainerDark = Color(0xFFFFD9E2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF222222)
val onBackgroundDark = Color(0xFFE7E0E8)
val surfaceDark = Color(0xFF222222)
val onSurfaceDark = Color(0xFFE7E0E8)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCBC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E8)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF66558E)
val surfaceDimDark = Color(0xFF141218)
val surfaceBrightDark = Color(0xFF3B383E)
val surfaceContainerLowestDark = Color(0xFF0F0D13)
val surfaceContainerLowDark = Color(0xFF1D1B20)
val surfaceContainerDark = Color(0xFF211F24)
val surfaceContainerHighDark = Color(0xFF2B292F)
val surfaceContainerHighestDark = Color(0xFF36343A)

val themeColor = Color(0xFF3D3A42)

val ShimmerColors = listOf(
    themeColor.copy(0.9f),
    themeColor.copy(0.2f),
    themeColor.copy(0.9f)
)
