name: Java CI with Gradle

on:
 push:
  branches:
   - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-results
          path: ./app
